name: Lint

on: pull_request

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint
        run: docker-compose run --rm app "yarn && yarn lint && yarn lint:readme"
